version: 2
updates:
  # Enable version updates for Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "marcioreck"
    assignees:
      - "marcioreck"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Allow security updates to be auto-merged
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
    # Ignore specific dependencies if needed
    ignore:
      # Example: ignore major version updates for stable dependencies
      # - dependency-name: "serde"
      #   update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "marcioreck"
    assignees:
      - "marcioreck"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Auto-merge minor and patch updates for GitHub Actions
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "direct"
        update-type: "minor"
      - dependency-type: "direct"
        update-type: "patch"

  # Python dependencies (for Python bindings)
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "marcioreck"
    assignees:
      - "marcioreck"
    commit-message:
      prefix: "deps(python)"
      include: "scope"
    allow:
      - dependency-type: "direct"
        update-type: "security"
