/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ReadResult {
  barcodeType: string
  data: string
  confidence: number
}

/** Generate a barcode and return it as bytes */
export function generateBarcode(barcodeType: string, data: string, format: string): Buffer
/** Generate a barcode and save it to a file */
export function generateBarcodeToFile(barcodeType: string, data: string, filename: string): void
/** Read the first barcode found in an image file */
export function readBarcodeFromFile(filename: string): ReadResult
/** Read all barcodes found in an image file */
export function readAllBarcodesFromFile(filename: string): Array<ReadResult>
/** Read barcode from image bytes */
export function readBarcodeFromBytes(bytes: Array<number>): ReadResult
/** Get version info */
export function getVersion(): string
/** Get supported barcode types */
export function getSupportedTypes(): Array<string>
/** Get supported export formats */
export function getSupportedFormats(): Array<string>
